### ISSUE TITLE
通过response.getOutputStream()方式下载图片，会报高危漏洞；

### ISSUE THREAD

**Issue by aLLeENSmith** [sourcebrella666/pinpoint_issues#1]
通过response.getOutputStream()方式下载图片，会报高危漏洞；

**[高危] 敏感信息泄露: 未分类隐私信息**

![image](https://user-images.githubusercontent.com/31880062/68824211-0335a400-06d1-11ea-8777-eb7943fb8227.png)
![image](https://user-images.githubusercontent.com/31880062/68824313-6e7f7600-06d1-11ea-9c18-85942515895b.png)

报告中给出的修复示例并不适用于该情况；
具体触发原因不明白；
并且相关代码未图片下载，应该并未涉及敏感信息泄露；
是否可能是误报的漏洞？

想请教一下该漏洞的成因，及对应的修复或者排除方案。

**Comment by mmyjona** [comment]
敏感信息泄露: 未分类隐私信息 这个检测器是用来审计可能的数据泄露的。例如这里可能是从数据库读取数据吐到文件。
这类敏感数据泄露的检测逻辑是找到可能的敏感数据来源和出口的路径，具体是否是敏感数据还是需要人工判断，因此命中率不高，但是覆盖全面。
可以在检查器配置中将这个检测器关掉。

**Comment by aLLeENSmith** [comment]
> 敏感信息泄露: 未分类隐私信息 这个检测器是用来审计可能的数据泄露的。例如这里可能是从数据库读取数据吐到文件。
> 这类敏感数据泄露的检测逻辑是找到可能的敏感数据来源和出口的路径，具体是否是敏感数据还是需要人工判断，因此命中率不高，但是覆盖全面。
> 可以在检查器配置中将这个检测器关掉。

OK，感谢解答；
